name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      # - name: Cache npm cache
      #   uses: actions/cache@v4
      #   with:
      #     path: "**/package-lock.json"
      #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-api-puce-tau.vercel.app/"
        with:
          build: npm run build
          start: npm start
